version: '3.1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_youbike
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: youbike
      MYSQL_USER: youbike-api
      MYSQL_PASSWORD: mysql@youbike
      MYSQL_DATABASE: youbike
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_general_ci
  ldap:
    image: itzg/apacheds
    container_name: apacheds
    ports:
    - 5487:10389
    - 10636:10636
